<a href="https://colab.research.google.com/github/siddharthaborgohain/pandas/blob/main/pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np     # ide: development tool  or integrated development environment
import pandas as pd    # import --> borrowing other libaryes

In [6]:
a=range(10)       # in a simple python
list(a)           # have to convert to list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
a=np.arange(10)   # in numpy we can directly show the range values
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a.reshape(5,2)    # reshaping in 5 rows and 2 columns

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
df=pd.DataFrame(a.reshape(5,2),columns=("col_1","col_2"),index=["Sachin","Sam","Sid","Ramesh","Suresh"])   # palce the data into a dataframe df

In [18]:
df

col_1  col_2
Sachin      0      1
Sam         2      3
Sid         4      5
Ramesh      6      7
Suresh      8      9

In [19]:
df.to_csv("new_file.csv")   # save the dataframe into a csv

In [30]:
df.loc["Sam"]           # take out any rows or indexs information using loc function

col_1    2
col_2    3
Name: Sam, dtype: int64

In [22]:
df.iloc[:,:1]             # to find out first columns using ilock

col_1
Sachin      0
Sam         2
Sid         4
Ramesh      6
Suresh      8

In [25]:
df.iloc[:,1:]              # to find the second column using ilock

col_2
Sachin      1
Sam         3
Sid         5
Ramesh      7
Suresh      9

In [26]:
df.iloc[:,:].values      # converting pandas to numpy

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
df.isnull().sum()

col_1    0
col_2    0
dtype: int64

In [28]:
df["col_1"].value_counts()

0    1
2    1
4    1
6    1
8    1
Name: col_1, dtype: int64

In [29]:
df["col_1"].unique()

array([0, 2, 4, 6, 8])