<a href="https://colab.research.google.com/github/siddharthaborgohain/pandas/blob/main/pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.arange(20)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x=a.reshape(5,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
x[3:,1:3]

array([[13, 14],
       [17, 18]])

In [ ]:
import pandas as pd
df=pd.DataFrame(x)

In [ ]:
df.iloc[3:,1:3]

1   2
3  13  14
4  17  18