<a href="https://colab.research.google.com/github/siddharthaborgohain/pandas/blob/main/Pandas1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [5]:
a=np.arange(0,20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
df=pd.DataFrame(a,index=["Row1","Row2","Row3","Row4","Row5"],columns=["Col1","col2",
                                                                   "col3",
                                                                   "col4"])

In [8]:
df.head()

Col1  col2  col3  col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    5 non-null      int64
 1   col2    5 non-null      int64
 2   col3    5 non-null      int64
 3   col4    5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes


In [10]:
df.describe()

Col1       col2       col3       col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [11]:
## indexing
## Columnname,rowindex[Loc] and [iloc]

In [12]:
df[['Col1','col2','col3']]

Col1  col2  col3
Row1     0     1     2
Row2     4     5     6
Row3     8     9    10
Row4    12    13    14
Row5    16    17    18

In [13]:
type(df[['Col1','col2','col3']])

pandas.core.frame.DataFrame

In [14]:
type(df['Col1'])

pandas.core.series.Series

In [15]:
df.loc['Row3']

Col1     8
col2     9
col3    10
col4    11
Name: Row3, dtype: int64

In [16]:
df.head()

Col1  col2  col3  col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [21]:
df.iloc[2:4,0:2]

Col1  col2
Row3     8     9
Row4    12    13

In [28]:
df.iloc [:,:]

Col1  col2  col3  col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [29]:
df.iloc[:,::3]

Col1  col4
Row1     0     3
Row2     4     7
Row3     8    11
Row4    12    15
Row5    16    19

In [30]:
# to convert DataFrame to arrays

In [31]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [32]:
df.isnull().sum()

Col1    0
col2    0
col3    0
col4    0
dtype: int64

In [33]:
null=[i for i in df.columns if df[i].isnull().any()]
null

[]

In [41]:
a=np.array([[2,np.nan,5],[4,5,np.nan]])

In [43]:
data=pd.DataFrame(a,columns=["col1","col2","col3"])
data

col1  col2  col3
0   2.0   NaN   5.0
1   4.0   5.0   NaN

In [44]:
data.isnull().sum()

col1    0
col2    1
col3    1
dtype: int64

In [45]:
[i for i in data.columns if data[i].isnull().any()]

['col2', 'col3']

In [47]:
data.isnull()

col1   col2   col3
0  False   True  False
1  False  False   True

In [52]:
data['col1'].value_counts()

2.0    1
4.0    1
Name: col1, dtype: int64

In [54]:
df.Col1.unique()

array([ 0,  4,  8, 12, 16])

In [61]:
df.head()

Col1  col2  col3  col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19